## Application
- name: "Download Crane"
  get_url:
    url: "https://github.com/google/go-containerregistry/releases/download/v0.6.0/go-containerregistry_Linux_x86_64.tar.gz"
    checksum: "sha256:b71c7ca16abff07787516efbe0c06c129d273f34490d6a85f815cec980fffe85"
    dest: "/tmp"

- name: "Extract Crane"
  become: yes
  unarchive:
    src: "/tmp/go-containerregistry_Linux_x86_64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    include:
      - crane
      - gcrane

- name: "Force App install"
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/app
    - /opt/blue-green-canary.tar.gz
  when: force_app_install | default(False)

- name: "Export blue-green-canary app to tarball"
  become: yes
  ansible.builtin.command:
    argv:
      - crane
      - export 
      - ghcr.io/kameshsampath/blue-green-canary 
      - /opt/blue-green-canary.tar.gz
    creates: /opt/blue-green-canary.tar.gz
  register: app_install

- name: "Extract App"
  become: yes
  unarchive:
    src: "/opt/blue-green-canary.tar.gz"
    dest: "/opt"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    creates: "/opt/app"
    include:
      - app
  when: app_install.rc == 0
  notify:
   - "Restart Blue Green Canary"

- name: "Copy 'Blue Green Canary App' env file"
  become: yes
  ansible.builtin.template:
    src: "app/.env.j2"
    dest: "/opt/app/.env.local"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  notify:
   - "Restart Blue Green Canary"
    
- name: "Create 'Blue Green Canary App' systemd unit"
  become: yes
  ansible.builtin.template:
    src: "app/blue-green-canary.service.j2"
    dest: "/etc/systemd/system/blue-green-canary.service"
    mode: '0644'
  notify:
   - "Restart Blue Green Canary"

- name: "Enable and start blue-green-canary.service service"
  become: yes
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    state: started
    name: blue-green-canary.service

- name: "Update Service Port"
  lineinfile:
    backrefs: yes
    regex: '^(\s*"start": "next start)(",)$'
    line: '\1 -p 8080\2'
    path: "/opt/app/package.json"
  notify:
   - "Restart Blue Green Canary"