- name: "Add the user 'coredns'"
  become: yes
  user:
    home: /var/lib/coredns
    system: true
    name: coredns
    state: present

- name: "Create AWS Credentials folder"
  become: yes
  file:
    path: "/var/lib/coredns/.aws"
    state: directory
    mode: "0744"
    owner: coredns
    group: coredns
  when: core_dns_use_k8s and create_aws_credentials_file

- name: Save AWS Credentials
  become: yes
  copy:
    dest: "/var/lib/coredns/.aws/credentials"
    content: |
      [default]
      aws_access_key_id     = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}
    owner: coredns
    group: coredns
    mode: "0744"
  when: core_dns_use_k8s and create_aws_credentials_file

- name: "Create Kubeconfig folder"
  become: yes
  file:
    state: directory
    path: /var/lib/coredns/.kube
    recurse: yes
    owner: coredns
    group: coredns
    mode: "0744"
  when: core_dns_use_k8s

- name: "Copy kubeconfig"
  become: yes
  copy:
    src: /vagrant/kubeconfig
    dest: /var/lib/coredns/.kube/config
    owner: coredns
    group: coredns
    mode: "0744"
    remote_src: yes
  when: core_dns_use_k8s

- name:  "Create CoreDNS Config Folder"
  become: yes
  file:
    path: /etc/coredns
    state: directory
  
- name: "Download CoreDNS"
  become: yes
  get_url:
    url: "https://github.com/coredns/coredns/releases/download/v{{coredns_version }}/coredns_{{ coredns_version }}_linux_amd64.tgz"
    checksum: "sha256:aede302ae591c9747040e10dc749d144df4812bd8bb141041d3d24c6204f309d"
    dest: /tmp

- name: "Extract CoreDNS"
  become: yes
  unarchive:
    src: "/tmp/coredns_{{ coredns_version }}_linux_amd64.tgz"
    dest: /usr/bin
    remote_src: yes

- name: "Create Corefile"
  become: yes
  template:
    src: "coredns/corefile.j2"
    dest: "{{ coredns_config_dir }}/Corefile"

- name: "Create CoreDNS Service"
  become: yes
  template:
    src: "coredns/coredns.service.j2"
    dest: "/etc/systemd/system/coredns.service"

- name: "Create coredns-sysusers.conf"
  become: yes
  template:
    src: "coredns/sysusers.conf.j2"
    dest: "/usr/lib/sysusers.d/coredns-sysusers.conf"

- name: "Create coredns-tmpfiles.conf"
  become: yes
  template:
    src: "coredns/tmpfiles.conf.j2"
    dest: "/usr/lib/tmpfiles.d/coredns-tmpfiles.conf"

- name: "Disable and stop systemd-resolved"
  become: yes
  service:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: "Delete old 'resolv.conf' link"
  become: yes
  file:
    path: "/etc/resolv.conf"
    state: absent

- name: "Create 'resolv.conf'"
  become: yes
  template:
    src: "coredns/resolv.conf.j2"
    dest: "/etc/resolv.conf"

- name: "Enable and start coredns service"
  become: yes
  service:
    name: coredns
    enabled: yes
    state: restarted
