- name: "Stop Istio"
  become: yes
  service:
    name: istio
    state: stopped
  ignore_errors: yes
  when: clean_istio_vm_files

- name: "kuebctl completions to  .bashrc"
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK kubectl"
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      complete -F __start_kubectl k
    dest: ~{{ ansible_user }}/.bashrc

- name: "Ensure kuebconfig directory"
  ansible.builtin.file:
    state: directory
    path: ~{{ansible_user}}/.kube
    mode: "0700"
    
- name: "Copy kubeconfig to vm"
  ansible.builtin.copy:
    src: "{{ kubeconfig_dir }}/config"
    dest: ~{{ansible_user}}/.kube/config
    mode: "700"

- name: "Update .vimrc"
  ansible.builtin.copy:
    content: |
      set ts=2
      set sts=2
      set sw=2
      set expandtab
      syntax on
      set ruler
      set number
    dest: ~{{ ansible_user }}/.vimrc

- name: "Copy .vimrc to root home"
  become: yes
  copy:
    remote_src: true
    src: ~{{ ansible_user }}/.vimrc
    dest: "/root/.vimrc"
    mode: 0644

- name: Get Current netplan
  ansible.builtin.slurp:
    src: /etc/netplan/50-cloud-init.yaml
  register: netplan_result
      
- name: "Set IPV4 facts"
  set_fact:
    default_ipv4_interface: "{{ ansible_default_ipv4.interface }}"
    default_ipv4_address: "{{ ansible_default_ipv4.address }}"
    default_ipv4_gateway: "{{ ansible_default_ipv4.gateway }}"
    current_netplan: "{{ netplan_result.content | b64decode | from_yaml }}"

- name: "Set Service IP Facts"
  set_fact:
    istio_svc_ip: "{{ default_ipv4_address }}"

- name: "Install {{ instance_app_image_version }} application"
  include_tasks: app.yml

- name: "Debug::ServiceIP"
  debug:
   var: istio_svc_ip

- name: "Setup Istio VM"
  include_tasks: configure_istio_vm.yml
  when: istio_enabled
