- hosts: localhost

  vars_files:
     - vars.yml

  tasks:
    - name: "Replace default to {{ inventory_hostname }}"
      debug:
        msg: '{{ "1.0.0" | regex_replace(semver_regexp,"v\g<major>") }}'
      vars:
        semver_regexp: '^(?P<major>\d+)\.(?P<minor>\d+).(?P<micro>\d+)-*(?P<patch>\w*)$'