apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: bgc
  namespace: gloo-mesh
spec:
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
        - name: istio-ingressgateway-service-account
          namespace: istio-system
          clusterName: cluster1
        - name: istio-ingressgateway-service-account
          namespace: istio-system
          clusterName: cluster2
  destinationSelector:
  - kubeServiceMatcher:
      namespaces:
      - blue-green-canary
      labels:
        app: blue-green-canary
      