workload_istio_ns: istio-system
workload_istio_gateway_ns: istio-gateways
workload_istio_svc_name: ingressgateway
istiod_nodeport_query: 'spec.ports[?name == `tcp-istiod` ].nodePort'
semver_regexp: '^(?P<major>\d+)\.(?P<minor>\d+).(?P<micro>\d+)-*(?P<patch>\w*)$'

force_app_install: no
use_nodeport: no

# Istio 
istio_enabled: yes
istio_vm_app: vm-demos-app
istio_vm_namespace: vm-demos
istio_vm_workdir: "/home/{{ ansible_user }}/istio-vm/files"
istio_vm_service_account: vm-service-account
istio_cluster_network: network1
istio_vm_network: vm-network
istio_cluster: cluster1
istiod_port: 15012
