- name: "Restart Istio"
  become: yes
  service:
    name: istio
    state: restarted
  tags:
   - istio
   - app

- name: "Restart App"
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ instance_app_image_name }}-app.service"
  tags:
   - app