k3s_version: v1.21.8+k3s1
k3s_server_location: /var/lib/rancher/k3s
k3s_cluster_cidr: 172.16.0.0/24
k3s_service_cidr: 172.18.0.0/20
k3s_deploy_calico_network_plugin: yes
extra_server_args: "--flannel-backend=none --cluster-cidr={{ k3s_cluster_cidr }} --service-cidr={{ k3s_service_cidr}} --disable-network-policy --disable=traefik"
